### ISSUE TITLE
support prometheus annotation for adding request parameters

### ISSUE THREAD

**Issue by eburghar** [poseidon/typhoon#1037]
**Description**

Some metrics endpoint like [vault](https://www.vaultproject.io/docs/configuration/telemetry#prometheus) needs a parameter to be added to the request (`format=prometheus`). It could be useful to support a generic way to add request parameters via annotation like

```yaml
annotations:
  prometheus.io/path: /v1/sys/metrics
  prometheus.io/port: 8200
  prometheus.io/param: format=prometheus
```

**Steps to Reproduce**

Feature request

**Expected behavior**

Be able to scrape endpoints that needs request parameters

**Environment**

Any

**Possible Solution**

Add relabeling like this one to the prometheus config

```yaml
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_param]
    action: replace
    regex: ([^=]+)=(.*)
    target_label: __param_$1
    replacement: $2
```
