### ISSUE TITLE
Kubelet needs SELinux mounts to allow auto volume relabeling

### ISSUE THREAD

**Issue by sedlund** [poseidon/typhoon#1123]
**Description**

Kubelet provides a mechanism for SELinux context relabeling but bind mounts in Typhoon are not supplied to allow it.

Also see: https://github.com/poseidon/typhoon/issues/935

**Steps to Reproduce**

Install Rook ceph storage.  Pods created with PVC will attach storage, but upon accessing the volume you receive:

```
kaf pod-ephemeral.yaml
pod/csi-rbd-demo-ephemeral-pod created

keti -n default csi-rbd-demo-ephemeral-pod -- bash

root@csi-rbd-demo-ephemeral-pod:/# df -h /myspace
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd0       976M  2.6M  958M   1% /myspace
root@csi-rbd-demo-ephemeral-pod:/# ls -ld /myspace
drwxrwxrwx. 3 root root 4096 Feb 17 15:27 /myspace
root@csi-rbd-demo-ephemeral-pod:/# ls -l /myspace
ls: cannot open directory '/myspace': Permission denied
root@csi-rbd-demo-ephemeral-pod:/#
```

> # /var/log/audit/audit.log

```
time->Thu Feb 17 16:20:42 2022
type=AVC msg=audit(1645114842.211:658): avc:  denied  { read } for  pid=9558 comm="ls" name="/" dev="rbd0" ino=2 scontext=system_u:system_r:container_t:s0:c591,c614 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=0
```

**Expected behavior**

SElinux relabeling to work properly.

**Environment**

* Platform: bare-metal
* OS: fedora-coreos 35
* Release: Typhoon v1.23.3

**Possible Solution**

From: https://github.com/rook/rook/issues/7575#issuecomment-1039954280

Explains the issue well.  Adding two bind mounts to the kubelet allows it to do relabeling.

```
  --volume /etc/selinux:/etc/selinux \
  --volume /sys/fs/selinux:/sys/fs/selinux
```

**Comment by log1cb0mb** [comment]
I completely forgot to submit PR for this which I had planned to do after figuring out the issue with rook/ceph dynamic PV mounts as detailed in my comment.
A bit related on the topic, as mentioned in https://github.com/rook/rook/issues/7575#issuecomment-1039954280 `--volume /var/lib/kubelet:/var/lib/kubelet:rshared,z` relabel flag for whole directory should also be removed otherwise it removes the container context specific labeling once kubelet restarts so I wonder if that is a typo because we do not seem to do the same for flatcar where docker is being used to run kubelet : https://github.com/poseidon/typhoon/blob/9aa99f1996b57b1a6df457621456ca8f6b6020f2/azure/flatcar-linux/kubernetes/cl/controller.yaml#L79

**Comment by dghubble** [comment]
@sedlund Can you provide a clear minimal repo? Not involving a whole rook, ceph, or other system. AWS CSI volumes work fine for example.

@log1cb0mb read more about `/var/lib/kubelet` relabel in the original commit https://github.com/poseidon/typhoon/commit/72c94f1c6afc17ef3fe52c73156aa3e9a04cce86. People trying to remove it in a personal fork (unsupported) leads to probelms like https://github.com/poseidon/typhoon/issues/1142

**Comment by sedlund** [comment]
@dghubble I've had to switch to a kubeadm based install because of https://github.com/containerd/containerd/issues/6767 so I can't carry the torch for this one sorry.

**Comment by solacelost** [comment]
@dghubble - I've gone ahead and built you a minimal reproducer.

### temptest.tf

```hcl
provider "aws" {
  region = "us-east-2"
  shared_credentials_files = [
    "/home/<your user>/.aws/credentials"
  ]
}

provider "ct" {}

terraform {
  required_providers {
    ct = {
      source  = "poseidon/ct"
      version = "0.10.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "4.5.0"
    }
  }
}

module "tempest" {
  source = "git::https://github.com/poseidon/typhoon//aws/fedora-coreos/kubernetes?ref=v1.23.6"

  # AWS
  cluster_name = "tempest"
  dns_zone     = "<your zone>"
  dns_zone_id  = "<your zone id>"

  # configuration
  ssh_authorized_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMP2QHu8XD6z4OOftE9J6z9CIc3lhnE1yKI460mzmCB3 jharmison@gmail.com"

  # optional
  worker_count = 2
  worker_type  = "t3.small"
}

resource "local_file" "kubeconfig-tempest" {
  content  = module.tempest.kubeconfig-admin
  filename = "/home/<your user>/.kube/tempest.config"
}
```

### aws-iam-secret.yaml

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kube-system
stringData:
  key_id: "<redacted>"
  access_key: "<redacted>"
```

### storageclass.yaml

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "50"
  encrypted: "true"
```

Commands:

```sh
# deploy cluster
terraform apply -auto-approve
export KUBECONFIG=~/.kube/tempest.config
kubectl get nodes -w
# wait for nodes to come ready
# apply ebs CSI
kubectl apply -f aws-iam-secret.yaml
kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.5"
kubectl rollout status -w deploy/ebs-csi-controller -n kube-system
kubectl apply -f storageclass.yaml
# run a simple test using the default CSI-backed storageclass
kubectl apply -f https://raw.githubusercontent.com/yasker/kbench/main/deploy/fio.yaml
kubectl logs -l kbench=fio -f
```

My output:

```console
$ kubectl logs -l kbench=fio -f
TEST_FILE: /volume/test
TEST_OUTPUT_PREFIX: test_device
TEST_SIZE: 30G
Benchmarking iops.fio into test_device-iops.json
fio: pid=0, err=13/file:filesetup.c:162, func=open, error=Permission denied
fio: pid=0, err=13/file:filesetup.c:162, func=open, error=Permission denied
fio: pid=0, err=13/file:filesetup.c:162, func=open, error=Permission denied
fio: pid=0, err=13/file:filesetup.c:162, func=open, error=Permission denied
```

**Comment by dghubble** [comment]
You're seeing that AWS CSI volumes show permission denied for file access? For simplicity, you should be able to remove kbench from the equation - just an alpine pod with the same mount and touch a file to see the same symptom. To dig into why, can you inspec the container's volume from the host? Something doesn't add up. Are you using `cri-o`?

AWS CSI volumes are used on Typhoon regularly. They get relabled as expected.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-ebs
provisioner: ebs.csi.aws.com
mountOptions:
  - context="system_u:object_r:container_file_t:s0"          <- notice
parameters:
  type: gp3
  fstype: ext4
  encrypted: "true"
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

```
sudo ls -alZ /var/lib/kubelet/pods/406d504b-f4d1-4eba-9b9b-9eeb0944e6bb/volumes/kubernetes.io~csi/pvc-8dfce316-d86e-437f-ae43-3e624b32a570/mount
total 66588
drwxr-xr-x. 3 root root system_u:object_r:container_file_t:s0     4096 Apr 25 16:01 .
drwxr-x---. 3 root root system_u:object_r:container_file_t:s0       40 Apr 21 03:28 ..
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0 68161536 Apr 25 16:01 database.sqlite
```

I've written about why `containerd` was chosen over `cri-o` after a long period of evaluation [here](https://github.com/poseidon/typhoon/issues/899#issuecomment-1010638811). I'm not looking to maintain both. Its important to me that Typhoon be what I actively run for real and what I can endorse.
