### ISSUE TITLE
CoreOS: validatingWebhookConfiguration: failed to load system roots and no roots provided; open /etc/ssl/certs/ca-certificates.crt: permission denied

### ISSUE THREAD

**Issue by JordanP** [poseidon/typhoon#1518]
**Description**

I try to create a CustomResource, for which there's a `validating_webhook_configuration`. When I `kubectl apply` I get 
```
Internal error occurred: failed calling webhook "vpooler.cnpg.io": failed to call webhook: 
Post "https://cnpg-webhook-service.cnpg-system.svc:443/validate-postgresql-cnpg-io-v1-pooler?timeout=10s": 
tls: failed to verify certificate: x509: failed to load system roots and no roots provided; open 
/etc/ssl/certs/ca-certificates.crt: permission denied
```

**Steps to Reproduce**

CoreOS, Typhoon 1.31. I am trying to deploy a [CNPG cluster](https://cloudnative-pg.io/). The installation of the CRDs and Operator works fine, but when I try to create the following resource:
```hcl
resource "kubernetes_manifest" "cluster" {
  depends_on = [module.yavin]
  manifest = {
    apiVersion = "postgresql.cnpg.io/v1"
    kind       = "Cluster"
    metadata = {
      name      = "cluster-example"
      namespace = "default"
    }
    spec = {
      instances = 3
      storage = {
        size = "1Gi"
      }
    }
  }
}
```
I get this 
![image](https://github.com/user-attachments/assets/3661e44c-68a0-4ebf-ab1b-565a530a71bd)

**Expected behavior**

I should be able to create that resource.

**Environment**

* Platform: google-cloud
* OS: fedora-coreos 
* Release: Typhoon v1.31
* Terraform: 1.5.7
* Plugins: 
* `+ provider registry.terraform.io/hashicorp/google v6.2.0 + provider registry.terraform.io/hashicorp/kubernetes v2.32.0`

**Possible Solution**
It seems the cert volumes (/etc/ssl/certs seems to be a symlink to /etc/pki) are mounted in the kube-api-server:
```
    Mounts:
      /etc/kubernetes/pki from secrets (ro)
      /etc/pki from etc-pki (ro)
      /etc/ssl/certs from etc-ssl (ro)
```
so it should work, but I am not sure it actually works.

**Comment by dghubble** [comment]
When you use admission controllers, they're responsible for running a server, generating self-signed TLS certificates, and populating caBundle with an appropriate CA certificate that clients will trust (or sometimes they have docs having your do this manually). The general host-level trusted CAs and the Kubernetes cluster's trusted CA's aren't for this. Its not for kube-apiserver or Typhoon to be involved in. https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#configure-admission-webhooks-on-the-fly

Best to consult with CNPG or the relevant custom extension provider depending on the situation

**Comment by JordanP** [comment]
I am not certain. This part of K8s documentation [here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#url) has:
```
Here is an example of a mutating webhook configured to call a URL (and expects the TLS certificate
 to be verified using system trust roots, so does not specify a caBundle):

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
webhooks:
- name: my-webhook.example.com
  clientConfig:
    url: "https://my-webhook.example.com:9443/my-webhook-path"
``` 
seems to say that having an empty `caBundle` is not forbidden and if `caBundle` is empty then `the TLS certificate [is] to be verified using system trust roots`

That interpretation seems to be inline with this [PR](https://github.com/kubernetes/kubernetes/pull/70138) or some part of the [k8s source code](https://github.com/kubernetes/kubernetes/blob/c9ff60dc68060891bf7352d70352b0ae2ed1cb5e/staging/src/k8s.io/api/admissionregistration/v1/types.go#L1185).
