### ISSUE TITLE
Q: k8s nodePort connectivity on DigitalOcean

### ISSUE THREAD

**Issue by mmisztal1980** [poseidon/typhoon#320]
## Question

- I'd apreciate an explanation on the behavior that I'm observing. I was expecting to be able to have connectivity to the ports from the `NodePort` range? Shouldn't that be a default behavior?
- I'd also apreciate some suggestions how to have this fixed? Is this an iptables issue?

### Environment

* Platform: digital-ocean
* OS: container-linux
* Ref: k8s vs 1.10
* Terraform: `terraform version` (reporting latest is **not** helpful)
* Plugins: Provider plugin versions (reporting latest is **not** helpful)

### Problem

- When attempting to call `traefik.my.domain` I'm getting a 503
- Attempting to telnet into any of my nodes' port 30080 is unsuccessful

### Desired Behavior

I'd expect the node-ports to be reachable.

### Steps to Reproduce

- I've provisioned the cluster using terraform (1x master, 3x nodes). 
- I've added a DigitalOcean LB with rules to route traffic:
  - 80 --> 30080
  - 442 --> 30443
- I've created a DNS A record so that `traefik.my.domain` points to the public LB
- I've added a DigitalOcean FW with rules to allow incoming traffic to nodes on ports:
  - 30080
  - 30443
- I've run `helm init` against my cluster
- I've installed traefik with helm (nodePort mode, with node ports : 30080 and 30443) and enabled the dashboard to be available under `traefik.my.domain`

**Comment by dghubble** [comment]
NodePort is part of Kubernetes conformance. If you don't trust that, you can verify it on your own with a simple deployment + service:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello
      phase: prod
  template:
    metadata:
      labels:
        name: hello
        phase: prod
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - name: http
              containerPort: 80
```

```
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort
  selector:
    name: hello
    phase: prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
```

SSH to a node. Verify you can curl the hello service via the service IP (i.e. cluster IP) for sanity.

```
kubectl get services
ssh core@some-node
curl 10.3.X.Y
```

Verify you can curl the hello service via the NodePort.

```
curl 127.0.0.1:30010
```

If you want to access the hello service from outside the cluster, punch a hole in the Digital Ocean firewall to allow the traffic. I've re-verified this works as expected. No bug to track here.

As far as your using helm and traefik, you should debug the situation using similar techniques.
