### ISSUE TITLE
Kubernetes v1.8.1 kube-apiserver memory leak

### ISSUE THREAD

**Issue by dghubble** [poseidon/typhoon#41]
## Bug

The Kubernetes hyperkube v1.8.1 apiserver (latest at time of writing) leaks memory (reported by https://github.com/kubernetes/kubernetes/issues/53485).

## Fix

This is slated to be fixed in v1.8.2 possibly with:

* https://github.com/kubernetes/kubernetes/pull/54225
* https://github.com/kubernetes/kubernetes/pull/53586

Notice the Google v1.8.2-beta.0 is not new enough.

## Meanwhile

If your clusters are running v1.7.7, favor waiting a few days for v1.8.2.

Otherwise:

* Use the heapster addon and `kubectl top pods -n kube-system` to keep an eye on usage.
* You may set a reasonable memory limit on the apiserver (relative to your available memory) with `kubectl edit daemonset kube-apiserver -n kube-system` (needs about 250Mi minimum). The pod will restart every few hours, but imo its safer than growing to the node memory max.

```
  name: kube-apiserver                                                                                                                                                                                   
    resources:                                                                                                                                                                                             
      limits:                                                                                                                                                                                              
        memory: 400Mi     
```

## Visualization

Prometheus / Grafan kube-apiserver on a v1.8.1.

![screenshot from 2017-10-20 22-34-00](https://user-images.githubusercontent.com/2253428/31848428-72465fb6-b5e7-11e7-8cd1-40fa6c8d1116.png)

With a 400Mi memory limit **set via edit**, the apiserver will get restarted every so often. Spikes are due to pod restarts, its not graceful.

![screenshot from 2017-10-21 07-40-42](https://user-images.githubusercontent.com/2253428/31852797-30bf85c6-b633-11e7-9b75-e84eafb7297c.png)
