### ISSUE TITLE
NTP on Container Linux baremetal

### ISSUE THREAD

**Issue by Keithsc** [poseidon/typhoon#416]
### Environment

* Platform: bare-metal
* OS: container-linux
* Release: v1.13.4
* Terraform: v0.11.11
* Plugins: terraform-provider-matchbox v0.2.3

### Problem

I have rook-0.9.3 (ceph) install on my cluster and it works well but am getting ntp errors "clock skew 0.420116s > max 0.05s" that I would like to resolve.  I have internal NTP servers that I would like to use but I am unsure how to get the cluster to use them.

I wrote a script that forced timesyncd to use my time-servers but I believe typesyncd is not accurate enough for ceph so want to try using ntpd instead. Unfortunatly am having trouble configuring NTP from within coreos so thought I would be best to ask here. 

### Desired Behavior
Enable a Typhoon cluster use a specific internal ntp server/s.

**Comment by dghubble** [comment]
Hey Keith, Container Linux hosts provision themselves according to a Container Linux Config. See the Container Linux docs on customizing your [NTP upstreams](https://coreos.com/os/docs/latest/configuring-date-and-timezone.html#configuring-ntpd). Typhoon has a unique feature to accept a list of [Container Linux Config snippets](https://typhoon.psdn.io/advanced/customization/#container-linux) that will be validated and merged into the main config, so you can provide a snippet for that purpose without Typhoon needing a special feature.

**Comment by dghubble** [comment]
Hope that guides you in the right direction. If you arrive at a useful CLC snippet and feel comfortable, it could help future askers to post it.

**Comment by Keithsc** [comment]
Hi, I wasn't aware of snippets, but they were simple to implement and worked perfectly each time !!cheers!!!
For me switching from timesyncd to ntpd didn't fix our ceph time problem because ntpd still wouldn't use the correct servers (I think this is a container Linux problem) so we're stuck with timesyncd.

I run the below snippets separately but I guess you can combine them into one ? Although I am a bit wary of screwing up the boot process and having to take a unplanned day trip to our datacetner. (We have cheap Dell ipmi cards that aren't the best).

Below are the snippets I am using for setting the timesyncd time servers and for wiping our data disks at boot time. 

storage:
  files:
    - path: /etc/systemd/timesyncd.conf
      filesystem: root
      mode: 0644
      contents:
        inline: |
          [Time]
          NTP=0.primary-timeserver.com 1.another-timeserver.com

storage:
  disks:
    - device: "/dev/sdb"
      wipe_table: true
    - device: "/dev/sdc"
      wipe_table: true

If someone else has the same ceph time issue then I also found that running the following on each nodes resolved our time drifting issue.

sudo timedatectl set-ntp true
sudo ntpdate primary-timeserver.com
sudo hwclock -w

**Comment by dghubble** [comment]
You can combine or divide snippets as desired, whatever makes sense. An Ignition document served to a machine is one document, so its the same result either way. Hopefully you end up finding a declarative way to do what you're hoping for eventually without scripting.

**Comment by elemental-lf** [comment]
@Keithsc, I also had the same problem with Ceph reporting clock skew with `timesyncd`. I switched to `ntpd` and this solved the clock skew messages for me. This is the snippet I'm using:
```yaml
# The Ceph monitor processes seem to have a problem with the way timesyncd
# synchronizes time and are reporting "clow skew". Switch to NTP.
# Configure at least four NTP servers to be able to detect a falseticker
# even when one of the other servers isn't reachable (anymore).
#
systemd:
  units:
    - name: systemd-timesyncd.service
      mask: true
    - name: ntpd.service
      enable: true

storage:
  files:
    - path: /etc/ntp.conf
      filesystem: root
      contents:
        inline: |
          server 0.coreos.pool.ntp.org
          server 1.coreos.pool.ntp.org
          server 2.coreos.pool.ntp.org
          server 3.coreos.pool.ntp.org
          restrict default nomodify nopeer noquery notrap limited kod
          restrict 127.0.0.1
          restrict [::1]
```
Is there a reason why you want to merge your different snippets? I've quite a few of these snippets each in a different file and feed these into the Typhoon module with some `terraform` magic . Each snippet/file corresponds to one system tweak which I then can enable for each system individually. `clc_snippets` for bare-metal were a godsend and saved me a lot of manual patching of the Typhoon module.
