### ISSUE TITLE
`hostPath` mounts using `subPath` do not work.

### ISSUE THREAD

**Issue by michas2** [poseidon/typhoon#546]
### Environment

* Platform: bare-metal
* OS: container-linux
* Release: v1.15.3
* Terraform: v0.12.6

### Problem

`hostPath` mounts using `subPath` do not work.
(Because of this a rook edgefs cluster is not able to run on my typhoon cluster.)

### Desired Behavior

They should work. :)

### Steps to Reproduce

Create a simple pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  nodeSelector:
    test: "true"
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test1
      name: test-volume1
    - mountPath: /test2
      name: test-volume2
      subPath: foo
  volumes:
  - name: test-volume1
    hostPath:
      path: /test/1
      type: DirectoryOrCreate
  - name: test-volume2
    hostPath:
      path: /test/2
      type: DirectoryOrCreate
```

Before creating the pod, the node looks like this:

```
$ ls -la /test
total 12
drwxr-xr-x.  2 root root 4096 Sep 20 16:28 .
drwxr-xr-x. 20 root root 4096 Sep 20 16:28 ..
```

After creating the pod the node looks like this:
```
$ ssh node2 ls -la /test
total 20
drwxr-xr-x.  3 root root 4096 Sep 20 16:30 .
drwxr-xr-x. 20 root root 4096 Sep 20 16:28 ..
drwxr-xr-x.  2 root root 4096 Sep 20 16:30 1
```

I would expect to find both `1` and `2/foo` there.

Inside the container I create some marker files:
```
root@test-pd:/# touch /test1/ping1
root@test-pd:/# touch /test2/ping2
```

On the node the first one ends up in the expected place but the second one does not:
```
node2 ~ # find / -name ping1 2>/dev/null
/test/1/ping1
node2 ~ # find / -name ping2 2>/dev/null
/var/lib/rkt/pods/run/5c756711-f8ed-4c86-b567-40e5833e11ee/overlay/deps-sha512-4a7060b8f7532cffba1973c3dd1383bbec62995f0d14f73cf1ca1f27a2bde67a/upper/hyperkube/test/2/foo/ping2
/var/lib/rkt/pods/run/5c756711-f8ed-4c86-b567-40e5833e11ee/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/kubelet/pods/ce7e240c-3389-46f9-9cb9-000819a9234f/volume-subpaths/test-volume2/test-container/1/ping2
/var/lib/rkt/pods/run/5c756711-f8ed-4c86-b567-40e5833e11ee/stage1/rootfs/opt/stage2/hyperkube/rootfs/test/2/foo/ping2
/var/lib/kubelet/pods/ce7e240c-3389-46f9-9cb9-000819a9234f/volume-subpaths/test-volume2/test-container/1/ping2
```

Is this a bug, or did I get the subpath feature completely wrong?

**Comment by michas2** [comment]
Just found a similar issue: https://github.com/kubernetes/kubernetes/issues/61456

**Comment by dghubble** [comment]
hostPath + subPath behavior is neccessarily host-dependent, there is not a standard here: https://github.com/cncf/k8s-conformance/tree/master/v1.15

`subPath` has a somewhat lengthy/[infamous](https://kubernetes.io/blog/2018/04/04/fixing-subpath-volume-vulnerability/) history in Kubernetes. Watch upstream issues [#61456](https://github.com/kubernetes/kubernetes/issues/61456) and [#72991](https://github.com/kubernetes/kubernetes/issues/72991) for news of any upstream changes, as its not specific to Typhoon.

In terms of practical advise, I generally recommend avoiding `hostPath` in cases you can. The idea of pods using a host location of your choice is error-prone: host mount behaviors are host-dependent (e.g. much of Container Linux is read-only), setup dependent (e.g. did you mount that RAID array at `/mnt/data` or no?), risky (e.g. don't leak host credentials, know what's in that location), and here we see `subPath` depending on the Kubelet isolation chosen. When you must use it, do so carefully.

Since `subPath` is geared toward mounting multiple directories from a single volume (e.g. a case typically for clouds where there really is a discrete PV resource), notice when using a `hostPath`, you could just specify the different "subpaths" as separate volumes (i.e. the whole `hostPath` idea is we take a host directory and treat it as though its a kind of volume). Unlike say an EBS volume (consumed as a single volume), you have some flexibiliy that allows you to achieve the goal of mounting disparate host locations into the pod.

Whether this meets Rook's needs or not would be a separate concern about which I don't have commentary.

**Comment by dghubble** [comment]
Here's an example where you avoid combining hostPath and subPath.

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - name: test1
      mountPath: /test1
    - name: test2-foo
      mountPath: /test2/foo
    - name: test2-bar
      mountPath: /test2/bar
  volumes:
  - name: test1
    hostPath:
      path: /test/1
  - name: test2-foo
    hostPath:
      path: /test/2/foo
  - name: test2-bar
    hostPath:
      path: /test/2/bar
```

Let's follow upstream for further discussions.
