### ISSUE TITLE
Hint: metrics for pods and nodes with prometheus-adapter sample

### ISSUE THREAD

**Issue by remoe** [poseidon/typhoon#610]
To install working metrics for pods and nodes based on Prometheus (Typhoon stock setup) and prometheus-adapter one need to do the following:

- Setup Typhoon with "enable_aggregation = true"

- fetch prometheus-adapter:

```console
helm fetch \
  --repo https://kubernetes-charts.storage.googleapis.com \
  --untar \
  --untardir ./charts \
  --version 1.4.0 \
  prometheus-adapter
```
- copy values:

```console
cp ./charts/prometheus-adapter/values.yaml \
  ./values/prometheus-adapter.yaml
  ```
- edit values ( ./values/prometheus-adapter.yaml): 

```yaml
affinity: {}

image:
  repository: directxman12/k8s-prometheus-adapter-amd64
  tag: v0.5.0
  pullPolicy: IfNotPresent

logLevel: 2

metricsRelistInterval: 1m

nodeSelector: {}

priorityClassName: ""

# Url to access prometheus
prometheus:
  url: http://prometheus.monitoring.svc.cluster.local
  port: null

replicas: 1

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources: {}
rules:
  default: true
  custom: []
  external: []
  resource: 
   cpu:
     containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>,container!="POD",container!="",pod!=""}[3m])) by (<<.GroupBy>>)
     nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>}[3m])) by (<<.GroupBy>>)
     resources:
       overrides:
         instance:
           resource: node
         namespace:
           resource: namespace
         pod:
           resource: pod
     containerLabel: container
   memory:
     containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,container!="POD",container!="",pod!=""}) by (<<.GroupBy>>)
     nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>}) by (<<.GroupBy>>)
     resources:
       overrides:
         instance:
           resource: node
         namespace:
           resource: namespace
         pod:
           resource: pod
     containerLabel: container
   window: 3m

service:
  annotations: {}
  port: 443
  type: ClusterIP

tls:
  enable: false

# Any extra volumes
extraVolumes: []

# Any extra volume mounts
extraVolumeMounts: []

tolerations: []

# Annotations added to the pod
podAnnotations: {}

```
- generate template:

```console
helm template --namespace monitoring --name prometheus-adapter \
  --values  ./values/prometheus-adapter.yaml \
  --output-dir ./manifests \
    ./charts/prometheus-adapter
```
- install on k8s:

```console
kubectl apply -n monitoring -f ./manifests
```

- After minutes, one can call:

```console
kubectl top nodes
kubectl top pods
```
