### ISSUE TITLE
null_resource.copy-worker Still creating... with Fedora CoreOS

### ISSUE THREAD

**Issue by dghubble** [poseidon/typhoon#915]
Fedora CoreOS 33 has stronger crypto defaults ([faq](https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_why_does_ssh_stop_working_after_upgrading_to_fedora_33)) while the Go language (and therefore Terraform plugins) hasn't yet added support for RSA SHA-2 (see https://github.com/golang/go/issues/37278).

Short/medium term, follow the Fedora CoreOS [guidance](https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_why_does_ssh_stop_working_after_upgrading_to_fedora_33). You can either use a non-RSA key (except Azure) or apply the workaround recommended by Fedora CoreOS as a [snippet](https://typhoon.psdn.io/advanced/customization/#fedora-coreos).

```yaml
variant: fcos
version: 1.1.0
storage:
  files:
    - path: /etc/ssh/sshd_config.d/10-insecure-rsa-keysig.conf
      mode: 0600
      contents:
        inline: |
          PubkeyAcceptedKeyTypes=+ssh-rsa
```

This issue is not tracking any planned action on Typhoon's part. But rather anticipating users not seeing the CHANGELOG.

### Symptom

You'll notice that provisioning clusters with Fedora CoreOS 33 hangs when trying to us an RSA key, because of the now stronger policies in Fedora.

```
module.foo.null_resource.copy-worker-secrets[0]: Still creating....
....
```

Bear in mind, if you are a new user, there are plenty of other reasons your SSH connections to bootstrap machines might not be working (e.g. ssh-agent, see docs).

Related: https://github.com/coreos/fedora-coreos-tracker/issues/699
